### ISSUE TITLE
Unknown Error with e.reason.startsWith

### ISSUE THREAD

**Issue by chris-short** [cmrunton/tls-dashboard#12]
Red Hat Enterprise Linux Server release 7.2 (Maipo)
node v0.10.42

Output of monitored_hosts.js:

```
var hosts = [
  'coreresearch.duke.edu',
  'dev1.coreresearch.duke.edu',
  'dev2.coreresearch.duke.edu',
  'eirb.mc.duke.edu',
  'forms.dukesmoking.com',
  'live.duhs.duke.edu',
  'ori.duke.edu',
  'qa.coreresearch.duke.edu',
  'redcap-val.dtmi.duke.edu',
  'redcap.dtmi.duke.edu',
  'veloseresearch.duhs.duke.edu',
  'volunteer.dcru.org'
];
module.exports = hosts;
```

Run of get_cert_info.js results in the following:

```
# node get_cert_info.js

/usr/share/node/tls-dashboard/node_app/get_cert_info.js:109
    }  else if (e.reason.startsWith('Host: '+element+'. is not in the cert\'s
                         ^
TypeError: Cannot call method 'startsWith' of undefined
    at ClientRequest.<anonymous> (/usr/share/node/tls-dashboard/node_app/get_cert_info.js:109:26)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1603:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:19)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
```

**Comment by solarchemist** [comment]
There is something in your `monitored_hosts.js` file.

Your file above (I copy-pasted) throws the same error on my system (Debian Jessie, node v6.2.1), but this subset worked without any errors:

```
var hosts = [
  'redcap-val.dtmi.duke.edu',
  'redcap.dtmi.duke.edu',
  'veloseresearch.duhs.duke.edu',
  'volunteer.dcru.org',
];
module.exports = hosts;
```

I guess you should check the `hosts` array line-by-line, perhaps some non-printing char somewhere or something like that?

**Comment by solarchemist** [comment]
I implemented a few more dashboards, and at this point I no longer believe the issue has to do with the the `monitored_hosts.js` file itself, but rather with the setup of the hosts we're pointing to.

I have tested a number of websites (all hosted on a non-SSL configured webhost) that all consistently cause `tls-dashboard` to throw the error observed by @chris-short, instead of just returning `host mismatch` or `connection refused` which was the case for non-SSL websites on a _different_ host (namely my own VPS).

So I'm leaning towards this being a webhost or DNS configuration issue. But I'm too inexperienced to tell if there's something `tls-dashboard` could do to alleviate the issue.

**Comment by maedox** [comment]
I'm getting the following, but only occasionally. I can't tell which of my hosts is causing it.

```
tls-dashboard/node_app/get_cert_info.js:109
    }  else if (e.reason.startsWith('Host: '+element+'. is not in the cert\'s altnames')) {
                        ^

TypeError: Cannot read property 'startsWith' of undefined
    at ClientRequest.<anonymous> (/home/paal/github/tls-dashboard/node_app/get_cert_info.js:109:25)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

My hosts:

```
var hosts = [
    'alpha.tracetracker.com',
    'app.tracetracker.com',
    'asset.tracetracker.com',
    'demo.tracetracker.com',
    'gns.tracetracker.com',
    'graylog.tracetracker.com',
    'herder.tracetracker.com',
    'hub.tracetracker.com',
    'nightly.tracetracker.com',
    'stage.tracetracker.com',
    'test.tracetracker.com',
    'tix-2.tracetracker.com',
    'www.tracetracker.com',
];
module.exports = hosts;
```

I'd wager the last one is the culprit, because it's protected by Cloudflare, and as you might know, they are applying lots of tricks to their TLS implementation.

**Comment by cmrunton** [comment]
Could be. I'm rewriting the error handling today to make things work a bit better with all the various types of failures. Unfortunately, the errors that Node emits are all over the map, depending on where in the TLS handshake it fails, so it's taking a little more work than I had hoped for. Thank goodness for [BadSSL](https://github.com/lgarron/badssl.com), because it gives me something reliable to test against.

**Comment by cmrunton** [comment]
Looks like in the initial list that @chris-short posted there were a number of self-signed certificates, and those get refused right now (I'll improve on that later). Fix is incoming to handle that error.
